### ISSUE TITLE
Keep THE NATION alive

### ISSUE THREAD

**Issue by MaximLobovsky** [Steffo99/keep-everything-alive#7]
un aereo vola lentamente sopra un paese, premendo spazio si sganciano i prodotti che devono atterrare sulle case sotto. Ogni paese ha i suoi prodotti es:
ITALIA -> pizza, spaghetti, mario (deve atterrare su un tubo verde)
GERMANIA -> birra, pretzel, shnitzel
FRANCIA -> baguette, formaggio, vino

**Comment by Steffo99** [comment]
Mancano le case poi è finito
