### ISSUE TITLE
keep THE FIRE alive

### ISSUE THREAD

**Issue by MaximLobovsky** [Steffo99/keep-everything-alive#8]
tutto pixeloso, clicca molto in fretta su un albero per tagliarlo, e metti i pezzettini caduti nel fuoco che va via via affievolendosi in una foresta buia e innevata

**Comment by Steffo99** [comment]
![](https://user-images.githubusercontent.com/1540885/79671128-3d4b2a80-81c8-11ea-8ffa-6472f4539de2.png)

**Comment by Steffo99** [comment]
Servirebbe uno sprite dell'accetta @MaxSensei666
